// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'countries_list_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

CountryListModel _$CountryListModelFromJson(Map<String, dynamic> json) =>
    CountryListModel(
      data: (json['data'] as List<dynamic>)
          .map((e) => Autogenerated.fromJson(e as Map<String, dynamic>))
          .toList(),
    );

Map<String, dynamic> _$CountryListModelToJson(CountryListModel instance) =>
    <String, dynamic>{
      'data': instance.data,
    };
