// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'country_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) =>
    Autogenerated(
      name: NameModel.fromJson(json['name'] as Map<String, dynamic>),
      cca2: json['cca2'] as String,
      capital:
          (json['capital'] as List<dynamic>?)?.map((e) => e as String).toList(),
      region: json['region'] as String?,
      subregion: json['subregion'] as String?,
      population: json['population'] as int?,
      continents: (json['continents'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      startOfWeek: json['startOfWeek'] as String?,
      landlocked: json['landlocked'] as bool?,
      timezones: (json['timezones'] as List<dynamic>?)
          ?.map((e) => e as String)
          .toList(),
      latlng: (json['latlng'] as List<dynamic>?)
          ?.map((e) => (e as num).toDouble())
          .toList(),
      maps: json['maps'] == null
          ? null
          : MapsModel.fromJson(json['maps'] as Map<String, dynamic>),
      flags: json['flags'] == null
          ? null
          : FlagsModel.fromJson(json['flags'] as Map<String, dynamic>),
      borders:
          (json['borders'] as List<dynamic>?)?.map((e) => e as String).toList(),
      car: json['car'] == null
          ? null
          : CarModel.fromJson(json['car'] as Map<String, dynamic>),
      coatOfArms: json['coatOfArms'] == null
          ? null
          : CoatOfArmModel.fromJson(json['coatOfArms'] as Map<String, dynamic>),
      postalCode: json['postalCode'] == null
          ? null
          : PostalModel.fromJson(json['postalCode'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'name': instance.name,
      'cca2': instance.cca2,
      'capital': instance.capital,
      'region': instance.region,
      'subregion': instance.subregion,
      'population': instance.population,
      'continents': instance.continents,
      'startOfWeek': instance.startOfWeek,
      'timezones': instance.timezones,
      'landlocked': instance.landlocked,
      'latlng': instance.latlng,
      'maps': instance.maps,
      'flags': instance.flags,
      'car': instance.car,
      'borders': instance.borders,
      'coatOfArms': instance.coatOfArms,
      'postalCode': instance.postalCode,
    };
