
import 'package:json_annotation/json_annotation.dart';
import 'package:untitled4/model/country_model.dart';
part 'countries_list_model.g.dart';

@JsonSerializable()
class CountryListModel {
  CountryListModel({
    required this.data,
  });
  factory CountryListModel.fromJson(Map<String, dynamic> json) =>
      _$CountryListModelFromJson(json);


  final List<Autogenerated> data;

  Map<String, dynamic> toJson() => _$CountryListModelToJson(this);
}
