import 'package:json_annotation/json_annotation.dart';
import 'package:untitled4/domain/entity.dart';
import 'package:untitled4/model/car_model.dart';
import 'package:untitled4/model/coat_of_arm_model.dart';
import 'package:untitled4/model/flags_model.dart';
import 'package:untitled4/model/maps_model.dart';
import 'package:untitled4/model/name_model.dart';
import 'package:untitled4/model/postal_model.dart';

part 'country_model.g.dart';

@JsonSerializable()
class Autogenerated extends CountryEntity{
  const Autogenerated({
   required NameModel  name,
    required String cca2,
    List<String>? capital,
     String? region,
    String? subregion,
     int? population,
    List<String>? continents,
     String? startOfWeek,
    bool? landlocked,
    List<String>? timezones,
    List<double>? latlng,
    MapsModel?  maps,
    FlagsModel?  flags,
    List<String>? borders,
    CarModel? car,
    CoatOfArmModel?  coatOfArms,
    PostalModel? postalCode,



  }) : super(
     name:name,
      cca2:cca2,
      capital:capital,
      region:region,
      subregion:subregion,
    population:population,
    continents:continents,
    startOfWeek:startOfWeek,
    landlocked:landlocked,
     timezones:timezones,
    latlng:latlng,
    maps:maps,
     flags:flags,
    car:car,
    borders:borders,
     coatOfArms:coatOfArms,
      postalCode:postalCode,


  );

  factory Autogenerated.fromJson(Map<String, dynamic> json) =>
      _$AutogeneratedFromJson(json);
  Map<String, dynamic> toJson() => _$AutogeneratedToJson(this);


}





























