// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'country_model.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Autogenerated _$AutogeneratedFromJson(Map<String, dynamic> json) =>
    Autogenerated(
      name: NameModel.fromJson(json['name'] as Map<String, dynamic>),
      tld: (json['tld'] as List<dynamic>).map((e) => e as String).toList(),
      cca2: json['cca2'] as String,
      ccn3: json['ccn3'] as String,
      cca3: json['cca3'] as String,
      cioc: json['cioc'] as String,
      independent: json['independent'] as String,
      status: json['status'] as String,
      unMember: json['unMember'] as String,
      currencies: json['currencies'] as Map<String, dynamic>,
      idd: json['idd'] as Map<String, dynamic>,
      capital:
          (json['capital'] as List<dynamic>).map((e) => e as String).toList(),
      altSpellings: (json['altSpellings'] as List<dynamic>)
          .map((e) => e as String)
          .toList(),
      region: json['region'] as String,
      subregion: json['subregion'] as String,
      languages: json['languages'] as Map<String, dynamic>,
      translations: json['translations'] as Map<String, dynamic>,
      latlng: json['latlng'] as List<dynamic>,
      landlocked: json['landlocked'] as bool,
      borders: json['borders'] as List<dynamic>,
      area: json['area'] as int,
      demonyms: json['demonyms'] as Map<String, dynamic>,
      flag: json['flag'] as String,
      maps: MapsModel.fromJson(json['maps'] as Map<String, dynamic>),
      population: json['population'] as String,
      gini: json['gini'] as Map<String, dynamic>,
      fifa: json['fifa'] as String,
      car: CarModel.fromJson(json['car'] as Map<String, dynamic>),
      timezones: json['timezones'] as List<dynamic>,
      continents: json['continents'] as List<dynamic>,
      flags: json['flags'] as Map<String, dynamic>,
      coatOfArms:
          CoatOfArmModel.fromJson(json['coatOfArms'] as Map<String, dynamic>),
      startOfWeek: json['startOfWeek'] as String,
      capitalInfo: json['capitalInfo'] as Map<String, dynamic>,
    );

Map<String, dynamic> _$AutogeneratedToJson(Autogenerated instance) =>
    <String, dynamic>{
      'name': instance.name,
      'tld': instance.tld,
      'cca2': instance.cca2,
      'ccn3': instance.ccn3,
      'cca3': instance.cca3,
      'cioc': instance.cioc,
      'independent': instance.independent,
      'status': instance.status,
      'unMember': instance.unMember,
      'currencies': instance.currencies,
      'idd': instance.idd,
      'capital': instance.capital,
      'altSpellings': instance.altSpellings,
      'region': instance.region,
      'subregion': instance.subregion,
      'languages': instance.languages,
      'translations': instance.translations,
      'latlng': instance.latlng,
      'landlocked': instance.landlocked,
      'borders': instance.borders,
      'area': instance.area,
      'demonyms': instance.demonyms,
      'flag': instance.flag,
      'maps': instance.maps,
      'population': instance.population,
      'gini': instance.gini,
      'fifa': instance.fifa,
      'car': instance.car,
      'timezones': instance.timezones,
      'continents': instance.continents,
      'flags': instance.flags,
      'coatOfArms': instance.coatOfArms,
      'startOfWeek': instance.startOfWeek,
      'capitalInfo': instance.capitalInfo,
    };
